/*
 * IDENTIFICATION:
 * stub generated Tue Jul  8 19:43:48 2014
 * with a MiG generated by bootstrap_cmds-86
 * OPTIONS: 
 *	KernelServer
 */

/* Module security */

#define	__MIG_check__Request__security_subsystem__ 1

#include "security_server.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#if	__MigKernelSpecificCode
#define msgh_request_port	msgh_remote_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_REMOTE(bits)
#define msgh_reply_port		msgh_local_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_LOCAL(bits)
#else
#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)
#endif /* __MigKernelSpecificCode */

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xmach_get_task_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_get_task_label_text
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_get_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_get_label_text
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmach_set_port_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmac_check_service
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmac_port_check_service_obj
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmac_port_check_access
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmac_label_new
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xmac_request_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mach_get_task_label_t__defined)
#define __MIG_check__Request__mach_get_task_label_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_get_task_label_t(__attribute__((__unused__)) __Request__mach_get_task_label_t *In0P)
{

	typedef __Request__mach_get_task_label_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_get_task_label_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_get_task_label */
mig_internal novalue _Xmach_get_task_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_get_task_label_t __Request;
	typedef __Reply__mach_get_task_label_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_get_task_label_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_get_task_label_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5200, "mach_get_task_label")
	__BeforeRcvRpc(5200, "mach_get_task_label")

#if	defined(__MIG_check__Request__mach_get_task_label_t__defined)
	check_result = __MIG_check__Request__mach_get_task_label_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_get_task_label_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mach_get_task_label(task, &OutP->label);
	space_deallocate(task);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(5200, "mach_get_task_label")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mach_get_task_label_text_t__defined)
#define __MIG_check__Request__mach_get_task_label_text_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_get_task_label_text_t(__attribute__((__unused__)) __Request__mach_get_task_label_text_t *In0P)
{

	typedef __Request__mach_get_task_label_text_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 512)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mach_get_task_label_text_t__policiesCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mach_get_task_label_text_t__policiesCnt(&In0P->policiesCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mach_get_task_label_text_t__policiesCnt__defined */
#if	__MigTypeCheck
	if ( In0P->policiesCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 512)) < In0P->policiesCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 512) + _WALIGN_(In0P->policiesCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->policies),  512);
		if (( strnlen(In0P->policies, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->policies),  512);
		if (( memchr(In0P->policies, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_get_task_label_text_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_get_task_label_text */
mig_internal novalue _Xmach_get_task_label_text
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t policiesOffset; /* MiG doesn't use it */
		mach_msg_type_number_t policiesCnt;
		char policies[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_get_task_label_text_t __Request;
	typedef __Reply__mach_get_task_label_text_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_get_task_label_text_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_get_task_label_text_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5201, "mach_get_task_label_text")
	__BeforeRcvRpc(5201, "mach_get_task_label_text")

#if	defined(__MIG_check__Request__mach_get_task_label_text_t__defined)
	check_result = __MIG_check__Request__mach_get_task_label_text_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_get_task_label_text_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mach_get_task_label_text(task, In0P->policies, OutP->label);
	space_deallocate(task);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;

#ifdef __LP64__
	{
		size_t strLength = strlen(OutP->label) + 1;
		if (strLength > 0xffffffff)
			MIG_RETURN_ERROR(OutP, MIG_BAD_ARGUMENTS);
		OutP->labelCnt = (mach_msg_type_number_t) strLength;
	}
#else
	OutP->labelCnt = (mach_msg_type_number_t) strlen(OutP->label) + 1;
#endif /* __LP64__ */
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 512) + (_WALIGN_((OutP->labelCnt + 3) & ~3));

	__AfterRcvRpc(5201, "mach_get_task_label_text")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mach_get_label_t__defined)
#define __MIG_check__Request__mach_get_label_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_get_label_t(__attribute__((__unused__)) __Request__mach_get_label_t *In0P)
{

	typedef __Request__mach_get_label_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_get_label_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_get_label */
mig_internal novalue _Xmach_get_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_port_name_t port;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_get_label_t __Request;
	typedef __Reply__mach_get_label_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_get_label_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_get_label_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5202, "mach_get_label")
	__BeforeRcvRpc(5202, "mach_get_label")

#if	defined(__MIG_check__Request__mach_get_label_t__defined)
	check_result = __MIG_check__Request__mach_get_label_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_get_label_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mach_get_label(task, In0P->port, &OutP->label);
	space_deallocate(task);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(5202, "mach_get_label")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mach_get_label_text_t__defined)
#define __MIG_check__Request__mach_get_label_text_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_get_label_text_t(__attribute__((__unused__)) __Request__mach_get_label_text_t *In0P)
{

	typedef __Request__mach_get_label_text_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 512)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mach_get_label_text_t__policiesCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mach_get_label_text_t__policiesCnt(&In0P->policiesCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mach_get_label_text_t__policiesCnt__defined */
#if	__MigTypeCheck
	if ( In0P->policiesCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 512)) < In0P->policiesCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 512) + _WALIGN_(In0P->policiesCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->policies),  512);
		if (( strnlen(In0P->policies, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->policies),  512);
		if (( memchr(In0P->policies, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_get_label_text_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_get_label_text */
mig_internal novalue _Xmach_get_label_text
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_port_name_t name;
		mach_msg_type_number_t policiesOffset; /* MiG doesn't use it */
		mach_msg_type_number_t policiesCnt;
		char policies[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_get_label_text_t __Request;
	typedef __Reply__mach_get_label_text_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_get_label_text_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_get_label_text_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5203, "mach_get_label_text")
	__BeforeRcvRpc(5203, "mach_get_label_text")

#if	defined(__MIG_check__Request__mach_get_label_text_t__defined)
	check_result = __MIG_check__Request__mach_get_label_text_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_get_label_text_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mach_get_label_text(task, In0P->name, In0P->policies, OutP->label);
	space_deallocate(task);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;

#ifdef __LP64__
	{
		size_t strLength = strlen(OutP->label) + 1;
		if (strLength > 0xffffffff)
			MIG_RETURN_ERROR(OutP, MIG_BAD_ARGUMENTS);
		OutP->labelCnt = (mach_msg_type_number_t) strLength;
	}
#else
	OutP->labelCnt = (mach_msg_type_number_t) strlen(OutP->label) + 1;
#endif /* __LP64__ */
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 512) + (_WALIGN_((OutP->labelCnt + 3) & ~3));

	__AfterRcvRpc(5203, "mach_get_label_text")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mach_set_port_label_t__defined)
#define __MIG_check__Request__mach_set_port_label_t__defined

mig_internal kern_return_t __MIG_check__Request__mach_set_port_label_t(__attribute__((__unused__)) __Request__mach_set_port_label_t *In0P)
{

	typedef __Request__mach_set_port_label_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 512)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mach_set_port_label_t__labelCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mach_set_port_label_t__labelCnt(&In0P->labelCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mach_set_port_label_t__labelCnt__defined */
#if	__MigTypeCheck
	if ( In0P->labelCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 512)) < In0P->labelCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 512) + _WALIGN_(In0P->labelCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->label),  512);
		if (( strnlen(In0P->label, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->label),  512);
		if (( memchr(In0P->label, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mach_set_port_label_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mach_set_port_label */
mig_internal novalue _Xmach_set_port_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_port_name_t name;
		mach_msg_type_number_t labelOffset; /* MiG doesn't use it */
		mach_msg_type_number_t labelCnt;
		char label[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mach_set_port_label_t __Request;
	typedef __Reply__mach_set_port_label_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mach_set_port_label_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mach_set_port_label_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5204, "mach_set_port_label")
	__BeforeRcvRpc(5204, "mach_set_port_label")

#if	defined(__MIG_check__Request__mach_set_port_label_t__defined)
	check_result = __MIG_check__Request__mach_set_port_label_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mach_set_port_label_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mach_set_port_label(task, In0P->name, In0P->label);
	space_deallocate(task);
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	__AfterRcvRpc(5204, "mach_set_port_label")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mac_check_service_t__defined)
#define __MIG_check__Request__mac_check_service_t__defined

mig_internal kern_return_t __MIG_check__Request__mac_check_service_t(__attribute__((__unused__)) __Request__mac_check_service_t *In0P, __attribute__((__unused__)) __Request__mac_check_service_t **In1PP, __attribute__((__unused__)) __Request__mac_check_service_t **In2PP, __attribute__((__unused__)) __Request__mac_check_service_t **In3PP)
{

	typedef __Request__mac_check_service_t __Request;
	__Request *In1P;
	__Request *In2P;
	__Request *In3P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mac_check_service_t__subjectCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_check_service_t__subjectCnt(&In0P->subjectCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_check_service_t__subjectCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->subjectCnt);
#if	__MigTypeCheck
	if ( In0P->subjectCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In0P->subjectCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In0P->subjectCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 512);

#if defined(__NDR_convert__int_rep__Request__mac_check_service_t__objectCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_check_service_t__objectCnt(&In1P->objectCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_check_service_t__objectCnt__defined */
	msgh_size_delta = _WALIGN_(In1P->objectCnt);
#if	__MigTypeCheck
	if ( In1P->objectCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In1P->objectCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In1P->objectCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In2PP = In2P = (__Request *) ((pointer_t) In1P + msgh_size_delta - 512);

#if defined(__NDR_convert__int_rep__Request__mac_check_service_t__serviceCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_check_service_t__serviceCnt(&In2P->serviceCnt, In2P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_check_service_t__serviceCnt__defined */
	msgh_size_delta = _WALIGN_(In2P->serviceCnt);
#if	__MigTypeCheck
	if ( In2P->serviceCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In2P->serviceCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In2P->serviceCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In3PP = In3P = (__Request *) ((pointer_t) In2P + msgh_size_delta - 512);

#if defined(__NDR_convert__int_rep__Request__mac_check_service_t__permCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_check_service_t__permCnt(&In3P->permCnt, In3P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_check_service_t__permCnt__defined */
#if	__MigTypeCheck
	if ( In3P->permCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 2048)) < In3P->permCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 2048) + _WALIGN_(In3P->permCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->subject),  512);
		if (( strnlen(In0P->subject, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->subject),  512);
		if (( memchr(In0P->subject, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In1P->object),  512);
		if (( strnlen(In1P->object, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In1P->object),  512);
		if (( memchr(In1P->object, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In2P->service),  512);
		if (( strnlen(In2P->service, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In2P->service),  512);
		if (( memchr(In2P->service, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In3P->perm),  512);
		if (( strnlen(In3P->perm, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In3P->perm),  512);
		if (( memchr(In3P->perm, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mac_check_service_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mac_check_service */
mig_internal novalue _Xmac_check_service
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t subjectOffset; /* MiG doesn't use it */
		mach_msg_type_number_t subjectCnt;
		char subject[512];
		mach_msg_type_number_t objectOffset; /* MiG doesn't use it */
		mach_msg_type_number_t objectCnt;
		char object[512];
		mach_msg_type_number_t serviceOffset; /* MiG doesn't use it */
		mach_msg_type_number_t serviceCnt;
		char service[512];
		mach_msg_type_number_t permOffset; /* MiG doesn't use it */
		mach_msg_type_number_t permCnt;
		char perm[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mac_check_service_t __Request;
	typedef __Reply__mac_check_service_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Request *In2P;
	Request *In3P;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mac_check_service_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mac_check_service_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5205, "mac_check_service")
	__BeforeRcvRpc(5205, "mac_check_service")

#if	defined(__MIG_check__Request__mac_check_service_t__defined)
	check_result = __MIG_check__Request__mac_check_service_t((__Request *)In0P, (__Request **)&In1P, (__Request **)&In2P, (__Request **)&In3P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mac_check_service_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mac_check_service(task, In0P->subject, In1P->object, In2P->service, In3P->perm);
	space_deallocate(task);
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	__AfterRcvRpc(5205, "mac_check_service")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mac_port_check_service_obj_t__defined)
#define __MIG_check__Request__mac_port_check_service_obj_t__defined

mig_internal kern_return_t __MIG_check__Request__mac_port_check_service_obj_t(__attribute__((__unused__)) __Request__mac_port_check_service_obj_t *In0P, __attribute__((__unused__)) __Request__mac_port_check_service_obj_t **In1PP, __attribute__((__unused__)) __Request__mac_port_check_service_obj_t **In2PP)
{

	typedef __Request__mac_port_check_service_obj_t __Request;
	__Request *In1P;
	__Request *In2P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 1536)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mac_port_check_service_obj_t__subjectCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_port_check_service_obj_t__subjectCnt(&In0P->subjectCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_port_check_service_obj_t__subjectCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->subjectCnt);
#if	__MigTypeCheck
	if ( In0P->subjectCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 1536)) < In0P->subjectCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 1536) + _WALIGN_(In0P->subjectCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 512);

#if defined(__NDR_convert__int_rep__Request__mac_port_check_service_obj_t__serviceCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_port_check_service_obj_t__serviceCnt(&In1P->serviceCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_port_check_service_obj_t__serviceCnt__defined */
	msgh_size_delta = _WALIGN_(In1P->serviceCnt);
#if	__MigTypeCheck
	if ( In1P->serviceCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 1536)) < In1P->serviceCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 1536) + _WALIGN_(In1P->serviceCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In2PP = In2P = (__Request *) ((pointer_t) In1P + msgh_size_delta - 512);

#if defined(__NDR_convert__int_rep__Request__mac_port_check_service_obj_t__permCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_port_check_service_obj_t__permCnt(&In2P->permCnt, In2P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_port_check_service_obj_t__permCnt__defined */
#if	__MigTypeCheck
	if ( In2P->permCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 1536)) < In2P->permCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 1536) + _WALIGN_(In2P->permCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->subject),  512);
		if (( strnlen(In0P->subject, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->subject),  512);
		if (( memchr(In0P->subject, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In1P->service),  512);
		if (( strnlen(In1P->service, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In1P->service),  512);
		if (( memchr(In1P->service, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In2P->perm),  512);
		if (( strnlen(In2P->perm, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In2P->perm),  512);
		if (( memchr(In2P->perm, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mac_port_check_service_obj_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mac_port_check_service_obj */
mig_internal novalue _Xmac_port_check_service_obj
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t subjectOffset; /* MiG doesn't use it */
		mach_msg_type_number_t subjectCnt;
		char subject[512];
		mach_port_name_t object;
		mach_msg_type_number_t serviceOffset; /* MiG doesn't use it */
		mach_msg_type_number_t serviceCnt;
		char service[512];
		mach_msg_type_number_t permOffset; /* MiG doesn't use it */
		mach_msg_type_number_t permCnt;
		char perm[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mac_port_check_service_obj_t __Request;
	typedef __Reply__mac_port_check_service_obj_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Request *In2P;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mac_port_check_service_obj_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mac_port_check_service_obj_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5206, "mac_port_check_service_obj")
	__BeforeRcvRpc(5206, "mac_port_check_service_obj")

#if	defined(__MIG_check__Request__mac_port_check_service_obj_t__defined)
	check_result = __MIG_check__Request__mac_port_check_service_obj_t((__Request *)In0P, (__Request **)&In1P, (__Request **)&In2P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mac_port_check_service_obj_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mac_port_check_service_obj(task, In0P->subject, In1P->object, In1P->service, In2P->perm);
	space_deallocate(task);
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	__AfterRcvRpc(5206, "mac_port_check_service_obj")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mac_port_check_access_t__defined)
#define __MIG_check__Request__mac_port_check_access_t__defined

mig_internal kern_return_t __MIG_check__Request__mac_port_check_access_t(__attribute__((__unused__)) __Request__mac_port_check_access_t *In0P, __attribute__((__unused__)) __Request__mac_port_check_access_t **In1PP)
{

	typedef __Request__mac_port_check_access_t __Request;
	__Request *In1P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 1024)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mac_port_check_access_t__serviceCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_port_check_access_t__serviceCnt(&In0P->serviceCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_port_check_access_t__serviceCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->serviceCnt);
#if	__MigTypeCheck
	if ( In0P->serviceCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 1024)) < In0P->serviceCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 1024) + _WALIGN_(In0P->serviceCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 512);

#if defined(__NDR_convert__int_rep__Request__mac_port_check_access_t__permCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_port_check_access_t__permCnt(&In1P->permCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_port_check_access_t__permCnt__defined */
#if	__MigTypeCheck
	if ( In1P->permCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 1024)) < In1P->permCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 1024) + _WALIGN_(In1P->permCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->service),  512);
		if (( strnlen(In0P->service, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->service),  512);
		if (( memchr(In0P->service, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In1P->perm),  512);
		if (( strnlen(In1P->perm, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In1P->perm),  512);
		if (( memchr(In1P->perm, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mac_port_check_access_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mac_port_check_access */
mig_internal novalue _Xmac_port_check_access
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_port_name_t subject;
		mach_port_name_t object;
		mach_msg_type_number_t serviceOffset; /* MiG doesn't use it */
		mach_msg_type_number_t serviceCnt;
		char service[512];
		mach_msg_type_number_t permOffset; /* MiG doesn't use it */
		mach_msg_type_number_t permCnt;
		char perm[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mac_port_check_access_t __Request;
	typedef __Reply__mac_port_check_access_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mac_port_check_access_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mac_port_check_access_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5207, "mac_port_check_access")
	__BeforeRcvRpc(5207, "mac_port_check_access")

#if	defined(__MIG_check__Request__mac_port_check_access_t__defined)
	check_result = __MIG_check__Request__mac_port_check_access_t((__Request *)In0P, (__Request **)&In1P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mac_port_check_access_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mac_port_check_access(task, In0P->subject, In0P->object, In0P->service, In1P->perm);
	space_deallocate(task);
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	__AfterRcvRpc(5207, "mac_port_check_access")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mac_label_new_t__defined)
#define __MIG_check__Request__mac_label_new_t__defined

mig_internal kern_return_t __MIG_check__Request__mac_label_new_t(__attribute__((__unused__)) __Request__mac_label_new_t *In0P)
{

	typedef __Request__mac_label_new_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 512)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mac_label_new_t__labelCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_label_new_t__labelCnt(&In0P->labelCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_label_new_t__labelCnt__defined */
#if	__MigTypeCheck
	if ( In0P->labelCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 512)) < In0P->labelCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 512) + _WALIGN_(In0P->labelCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->label),  512);
		if (( strnlen(In0P->label, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->label),  512);
		if (( memchr(In0P->label, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mac_label_new_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mac_label_new */
mig_internal novalue _Xmac_label_new
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t labelOffset; /* MiG doesn't use it */
		mach_msg_type_number_t labelCnt;
		char label[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mac_label_new_t __Request;
	typedef __Reply__mac_label_new_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mac_label_new_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mac_label_new_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5208, "mac_label_new")
	__BeforeRcvRpc(5208, "mac_label_new")

#if	defined(__MIG_check__Request__mac_label_new_t__defined)
	check_result = __MIG_check__Request__mac_label_new_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mac_label_new_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mac_label_new(task, &OutP->name, In0P->label);
	space_deallocate(task);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(5208, "mac_label_new")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__security_subsystem__
#if !defined(__MIG_check__Request__mac_request_label_t__defined)
#define __MIG_check__Request__mac_request_label_t__defined

mig_internal kern_return_t __MIG_check__Request__mac_request_label_t(__attribute__((__unused__)) __Request__mac_request_label_t *In0P)
{

	typedef __Request__mac_request_label_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 512)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__mac_request_label_t__serviceCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__mac_request_label_t__serviceCnt(&In0P->serviceCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__mac_request_label_t__serviceCnt__defined */
#if	__MigTypeCheck
	if ( In0P->serviceCnt > 512 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 512)) < In0P->serviceCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 512) + _WALIGN_(In0P->serviceCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
#if __MigKernelSpecificCode
		size_t strnlen_limit;
#else
		size_t memchr_limit;
#endif /* __MigKernelSpecificCode */

#if __MigKernelSpecificCode
		strnlen_limit = min((msg_limit - In0P->service),  512);
		if (( strnlen(In0P->service, strnlen_limit) >= 512 + 1 ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#else
		memchr_limit = min((msg_limit - In0P->service),  512);
		if (( memchr(In0P->service, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
#endif /* __MigKernelSpecificCode */
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__mac_request_label_t__defined) */
#endif /* __MIG_check__Request__security_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine mac_request_label */
mig_internal novalue _Xmac_request_label
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_port_name_t subject;
		mach_port_name_t object;
		mach_msg_type_number_t serviceOffset; /* MiG doesn't use it */
		mach_msg_type_number_t serviceCnt;
		char service[512];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__mac_request_label_t __Request;
	typedef __Reply__mac_request_label_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__mac_request_label_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__mac_request_label_t__defined */

#if	__MigKernelSpecificCode
#else
#endif /* __MigKernelSpecificCode */
	ipc_space_t task;

	__DeclareRcvRpc(5209, "mac_request_label")
	__BeforeRcvRpc(5209, "mac_request_label")

#if	defined(__MIG_check__Request__mac_request_label_t__defined)
	check_result = __MIG_check__Request__mac_request_label_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__mac_request_label_t__defined) */

	task = convert_port_to_space(In0P->Head.msgh_request_port);

	OutP->RetCode = mac_request_label(task, In0P->subject, In0P->object, In0P->service, &OutP->newlabel);
	space_deallocate(task);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}
#if	__MigKernelSpecificCode
#endif /* __MigKernelSpecificCode */

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(5209, "mac_request_label")
}



/* Description of this subsystem, for use in direct RPC */
const struct security_subsystem security_subsystem = {
	security_server_routine,
	5200,
	5210,
	(mach_msg_size_t)sizeof(union __ReplyUnion__security_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_get_task_label, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_get_task_label_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_get_task_label_text, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_get_task_label_text_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_get_label, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_get_label_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_get_label_text, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_get_label_text_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmach_set_port_label, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mach_set_port_label_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmac_check_service, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mac_check_service_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmac_port_check_service_obj, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mac_port_check_service_obj_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmac_port_check_access, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mac_port_check_access_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmac_label_new, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mac_label_new_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xmac_request_label, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__mac_request_label_t)},
	}
};

mig_external boolean_t security_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;

	if ((InHeadP->msgh_id > 5209) || (InHeadP->msgh_id < 5200) ||
	    ((routine = security_subsystem.routine[InHeadP->msgh_id - 5200].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t security_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 5200;

	if ((msgh_id > 9) || (msgh_id < 0))
		return 0;

	return security_subsystem.routine[msgh_id].stub_routine;
}
